extend = "ruff-base.toml"

# These are files to exclude for this project.
extend-exclude = [
  "*.ipynb",  # commonly not ruff-compliant
]

# These are rules that commonly cause many ruff warnings. Code will be improved by
# incrementally fixing code to adhere to these rules, but for practical purposes they
# can be ignored by uncommenting each one. You can also add to this list as needed.
lint.extend-ignore = [
  "B905", # `zip()` without an explicit `strict=` parameter
  "PLR0912", # Too many branches
]

[lint.extend-per-file-ignores]
"**/tests/test_*.py" = ["PLW0602", "PLW0603"]
